version: "3"

services:
  web:
    build: .
    container_name: api
    command: "bin/setup && rails server"
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
    env_file: .env.development
    tty: true
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: postgresql
    env_file: .env.database

  cache:
    image: redis
    container_name: redis
    command: "redis-server"
