default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: rails_graphql_development

test:
  <<: *default
  database: rails_graphql_test
#
production:
  <<: *default
  database: rails_graphql_production
  username: rails_graphql
  password: <%= ENV["RAILS_GRAPHQL_DATABASE_PASSWORD"] %>
